include:
  - board: xiao_ble//zmk
    shield: totem_left
    # remove cmake-args to "undongle"
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: xiao_ble//zmk
    shield: totem_right
    # remove cmake-args to "undongle"
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: xiao_ble//zmk
    shield: totem_dongle
    # reset firmware
  - board: xiao_ble//zmk
    shield: settings_reset
# there is no settingsreset (needed) for the XIAO
